<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('penilaians', function (Blueprint $table) {
            $table->id();
            $table->string('id_pengajuan')->unique();
            $table->text('nilai');
            $table->text('f1');
            $table->text('n1');
            $table->text('f2');
            $table->text('n2');
            $table->text('f3');
            $table->text('n3');
            $table->text('f4');
            $table->text('n4');
            $table->text('f5');
            $table->text('n5');
            $table->text('f6');
            $table->text('n6');
            $table->text('f7');
            $table->text('n7');
            $table->text('f8');
            $table->text('n8');
            $table->text('f9');
            $table->text('n9');
            $table->text('f10');
            $table->text('n10');
            $table->text('f11');
            $table->text('n11');
            $table->text('f12');
            $table->text('n12');
            $table->text('f13');
            $table->text('n13');
            $table->text('f14');
            $table->text('n14');
            $table->text('f15');
            $table->text('n15');
            $table->text('f16');
            $table->text('n16');
            $table->text('f17');
            $table->text('n17');
            $table->text('f18');
            $table->text('n18');
            $table->text('f19');
            $table->text('n19');
            $table->text('f20');
            $table->text('n20');
            $table->text('f21');
            $table->text('n21');
            $table->text('f22');
            $table->text('n22');
            $table->text('f23');
            $table->text('n23');
            $table->text('f24');
            $table->text('n24');
            $table->text('f25');
            $table->text('n25');
            $table->text('f26');
            $table->text('n26');
            $table->text('f27');
            $table->text('n27');
            $table->text('f28');
            $table->text('n28');
            $table->text('f29');
            $table->text('n29');
            $table->text('f30');
            $table->text('n30');
            $table->text('f31');
            $table->text('n31');
            $table->text('f32');
            $table->text('n32');
            $table->text('f33');
            $table->text('n33');
            $table->text('f34');
            $table->text('n34');
            $table->text('f35');
            $table->text('n35');
            $table->text('f36');
            $table->text('n36');
            $table->text('f37');
            $table->text('n37');
            $table->text('f38');
            $table->text('n38');
            $table->text('f39');
            $table->text('n39');
            $table->text('f40');
            $table->text('n40');
            $table->text('f41');
            $table->text('n41');
            $table->text('f42');
            $table->text('n42');
            $table->text('f43');
            $table->text('n43');
            $table->text('f44');
            $table->text('n44');
            $table->text('f45');
            $table->text('n45');
            $table->text('f46');
            $table->text('n46');
            $table->text('f47');
            $table->text('n47');
            $table->text('f48');
            $table->text('n48');
            $table->text('f49');
            $table->text('n49');
            $table->text('f50');
            $table->text('n50');
            $table->text('f51');
            $table->text('n51');
            $table->text('f52');
            $table->text('n52');
            $table->text('f53');
            $table->text('n53');
            $table->text('f54');
            $table->text('n54');
            $table->text('f55');
            $table->text('n55');
            $table->text('f56');
            $table->text('n56');
            $table->text('f57');
            $table->text('n57');
            $table->text('f58');
            $table->text('n58');
            $table->text('f59');
            $table->text('n59');
            $table->text('f60');
            $table->text('n60');
            $table->text('f61');
            $table->text('n61');
            $table->text('f62');
            $table->text('n62');
            $table->text('f63');
            $table->text('n63');
            $table->text('f64');
            $table->text('n64');
            $table->text('f65');
            $table->text('n65');
            $table->text('f66');
            $table->text('n66');
            $table->text('f67');
            $table->text('n67');
            $table->text('f68');
            $table->text('n68');
            $table->text('f69');
            $table->text('n69');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('penilaians');
    }
};
